{% set name = "nbsmoke" %}
{% set version = "0.2.8" %}
{% set sha256 = "eeda6c59b61130b9116a3d935e7c80ec5f617d7db8918d23289b2426efa229eb" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - beautifulsoup4
    - ipykernel
    - jupyter_client
    - nbconvert
    - nbformat
    - pyflakes
    - pytest >=3.1.1
    - python >=2.7
    - requests

test:
  imports:
    - nbsmoke
  # TODO: once nbsmoke's tests are moved into the package, can add the following
  #commands:
  #  - pytest --pyargs nbsmoke # or similar

about:
  home: http://github.com/pyviz/nbsmoke
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Basic notebook checks. Do they run? Do they contain lint?'

extra:
  recipe-maintainers:
    - ceball
    - jsignell
