travis:
  secure:
    BINSTAR_TOKEN: NI9J50y2mdimLeBQG7JUcYzdAMsM2Nb9F64BHzJPf+a9u+3XhQyih5gcAVoy3IsPstgjD28UNs16tv+iV7J3gNe3aoP0c7THtpcLmLiVKS3reGnwfXIQ4TAZ6wZxh6RIbXsKqv4VaIZuXFh+2YLo5ci+mvDLHv6yKyJWAGh4jVreFUWUaOPfkXFYmg2w6tfi1jMENUWp1EWHR9e4fjS68Bm3S3C8AEuDSST8t6Wnx1eORkDaqjP1OwM8wgz/7ZJR6cP4/0yuv2PCmkSVSbKWJuD3UALxXXmrnq0oXZDuULcw0K8SgRGWbqnDcozM9yKf9PA64vHiVLwIgx9d08JmNEcah53c8teE1URJx5JwONsp2+H3gUmwshp1Es69FuRlsrtairyccNAEfILnvSnZXWdb/f7lFRKtcyPCjTlFGBRpparwwlcpGXbCvr0bfx+aT6c7NCPlD7e/D6ZJ7sHd9Ckhx6e1h/9tPlqd8ACUwKA4GNEQUI0xMQi9Dl5GXsHTluwnyy6m/wxNmfq2Ui/EvNCUlQUzDmpZMYgWccVU4v76PQyMxV9y4dqDsNnE8Hk4EZpkVhHQAf0q0OX4PrVgdPmKO0O7ObS4hO8iXbHphZQ6ax16j7OwFSaa+qLA+mxjDCqhlaNNzZJL6+BIY6evRI0K/dAzm6d/yvElu8XhwC4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
